/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-27 09:21:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin.product;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/admin/_header.jsp", Long.valueOf(1724662380189L));
    _jspx_dependants.put("/WEB-INF/admin/_footer.jsp", Long.valueOf(1724662380189L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>상품목록</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/farm/css/admin/product/list.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id = \"wrapper\">\r\n");
      out.write("        \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farm/css/admin/_header.css\">\r\n");
      out.write("<header>\r\n");
      out.write("    <a href=\"#\"></a>\r\n");
      out.write("    <span>HOME | 로그아웃 | 고객센터</span>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <main>\r\n");
      out.write("            <aside>\r\n");
      out.write("                <h3 class=\"main_function\"><p>주요기능</p></h3>\r\n");
      out.write("                <ul class=\"aside-list\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p class=\"tit\">상품관리</p>\r\n");
      out.write("                        <a href=\"#\" class=\"contents1\">┗ 상품목록</a><br>\r\n");
      out.write("                        <a href=\"#\" class=\"contents2\">┗ 상품등록</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p class=\"tit\">주문관리</p>\r\n");
      out.write("                        <a href=\"#\" class=\"contents\">┗ 주문목록</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p class=\"tit\">회원관리</p>\r\n");
      out.write("                        <a href=\"/farm/admin/user/list.do\" class=\"contents\">┗ 회원목록</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <section>\r\n");
      out.write("                <h4 class=\"product_list\">상품목록</h4>\r\n");
      out.write("                <article class=\"h1\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <tbody>      \r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><input type=\"checkbox\"></th>\r\n");
      out.write("                                <th>사진</th>\r\n");
      out.write("                                <th>상품번호</th>  \r\n");
      out.write("                                <th>상품명</th>  \r\n");
      out.write("                                <th>구분</th>\r\n");
      out.write("                                <th>가격</th>\r\n");
      out.write("                                <th>재고</th>\r\n");
      out.write("                                <th>등록일</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><data value=\"\"><input type=\"checkbox\"></data></td>\r\n");
      out.write("                                <td><data value=\"\"><img src=\"/farm/img/admin/sample_item1.jpg\"></data></td>\r\n");
      out.write("                                <td><data value=\"\">1011</data></td>\r\n");
      out.write("                                <td><data value=\"\">사과 500g</data></td>\r\n");
      out.write("                                <td><data value=\"\">과일</data></td>\r\n");
      out.write("                                <td><data value=\"\">4,000원</data></td>\r\n");
      out.write("                                <td><data value=\"\">100</data></td>\r\n");
      out.write("                                <td><data value=\"\">2023-01-01</data></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div id=\"container\">\r\n");
      out.write("                        <p class=\"select_del\">선택삭제</p>\r\n");
      out.write("                        <a href=\"#\" class=\"reg\">상품등록</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"page_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <span class=\"underline\">[1]</span>\r\n");
      out.write("                            <span>[2]</span>\r\n");
      out.write("                            <span>[3]</span>\r\n");
      out.write("                            <span>[4]</span>\r\n");
      out.write("                            <span>[5]</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </article>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farm/css/admin/_footer.css\">\r\n");
      out.write("<footer>\r\n");
      out.write("    <p class=copyright>\r\n");
      out.write("        Copyright(C)Farmstory All rights reserved.FARMSTORY ADMINISTRATOR Version 1.0.1\r\n");
      out.write("    </p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
