/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-27 09:21:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>상품등록</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font: normal 12px 'Inter';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul, ol {list-style: none;}\r\n");
      out.write("        a {text-decoration: none; color: #111;}\r\n");
      out.write("        input, textarea {outline: none;}\r\n");
      out.write("\r\n");
      out.write("        #wrapper {\r\n");
      out.write("            width : 100%;\r\n");
      out.write("            height : 743px;\r\n");
      out.write("            margin : 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /************************ Header ************************/\r\n");
      out.write("        header{\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 980px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            left: 470px;\r\n");
      out.write("            top: 0px;\r\n");
      out.write("            background: url(../img/admin/admin_bg.jpg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header > a {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 170px;\r\n");
      out.write("            height: 32px;\r\n");
      out.write("            left: 12px;\r\n");
      out.write("            top: 12px;\r\n");
      out.write("            background: url(../img/admin/admin_logo.jpg) no-repeat;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header > span {\r\n");
      out.write("            width: 149px;\r\n");
      out.write("            height: 14px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 13px;\r\n");
      out.write("            left: 819px;\r\n");
      out.write("            font-size: 11px; /*원래는 12로 변경해야 함*/\r\n");
      out.write("            color: white;\r\n");
      out.write("            line-height: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /************************ Main ************************/\r\n");
      out.write("        main{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 980px;\r\n");
      out.write("            height: 644px;\r\n");
      out.write("            left: 470px;\r\n");
      out.write("            top: 60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /************************ Aside ************************/\r\n");
      out.write("        aside{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 176px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            left: 0px;\r\n");
      out.write("            top: 0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main_function {\r\n");
      out.write("            width: 156px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("            border: 1px solid #CCCCCC;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            background: #E5E5E5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        aside > h3 > p {\r\n");
      out.write("            width: 56px;\r\n");
      out.write("            height: 15px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 7px;\r\n");
      out.write("            left: 21px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            line-height: 17px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .aside-list {\r\n");
      out.write("            width: 156px;\r\n");
      out.write("            height: 234px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 40px;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tit {\r\n");
      out.write("            width: 48px;\r\n");
      out.write("            height: 14px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li:nth-child(1) {\r\n");
      out.write("            width: 124px;\r\n");
      out.write("            height: 72px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 26px;\r\n");
      out.write("            left: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        li:nth-child(2) {\r\n");
      out.write("            width: 124px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 108px;\r\n");
      out.write("            left: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        li:nth-child(3) {\r\n");
      out.write("            width: 124px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 168px;\r\n");
      out.write("            left: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contents {\r\n");
      out.write("            width: 124px;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 28px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contents1 {\r\n");
      out.write("            width: 124px;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 28px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contents2 {\r\n");
      out.write("            width: 124px;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li > p, li > a {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /************************ section ************************/\r\n");
      out.write("       section{\r\n");
      out.write("            width: 804px;\r\n");
      out.write("            height: 658px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 176px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("         section > article {\r\n");
      out.write("             width: 784px;\r\n");
      out.write("             height: 193px;\r\n");
      out.write("             position: relative;\r\n");
      out.write("            } \r\n");
      out.write("            \r\n");
      out.write("            table {\r\n");
      out.write("                width: 784px;\r\n");
      out.write("                height: 170px;\r\n");
      out.write("                border-top: 2px solid black;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            th, td {\r\n");
      out.write("                border: 0px 0px 1px 0px;\r\n");
      out.write("                border-bottom: 1px dotted;\r\n");
      out.write("                height: 42px;\r\n");
      out.write("            }\r\n");
      out.write("            .plus {\r\n");
      out.write("                 float: right;\r\n");
      out.write("                margin-top: -30px;\r\n");
      out.write("            }\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("        /************************ Footer ************************/\r\n");
      out.write("        footer{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 980px;\r\n");
      out.write("            height: 39px;\r\n");
      out.write("            left: 470px;\r\n");
      out.write("            right: 470px;\r\n");
      out.write("            top: 704px;\r\n");
      out.write("\r\n");
      out.write("            background: #353535;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .copyright{\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-top: 8px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id = \"wrapper\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <a href=\"#\"></a>\r\n");
      out.write("            <span>HOME | 로그아웃 | 고객센터</span>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <main>\r\n");
      out.write("            <aside>\r\n");
      out.write("                <h3 class=\"main_function\"><p>주요기능</p></h3>\r\n");
      out.write("                <ul class=\"aside-list\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p class=\"tit\">상품관리</p>\r\n");
      out.write("                        <a href=\"/farm/admin/product/list.do\" class=\"contents1\">┗ 상품목록</a><br>\r\n");
      out.write("                        <a href=\"/farm/admin/product/register.do\" class=\"contents2\">┗ 상품등록</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p class=\"tit\">주문관리</p>\r\n");
      out.write("                        <a href=\"#\" class=\"contents\">┗ 주문목록</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p class=\"tit\">회원관리</p>\r\n");
      out.write("                        <a href=\"/farm/admin/user/list.do\" class=\"contents\">┗ 회원목록</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <section>\r\n");
      out.write("                <h4>관리자 메인</h4>\r\n");
      out.write("                <h4>상품현황</h4>\r\n");
      out.write("                <div class=\"plus\">+더보기</div>\r\n");
      out.write("                <article class=\"h1\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>    \r\n");
      out.write("                        <tr>\r\n");
      out.write("                                <th>상품번호</th>\r\n");
      out.write("                                <th>상품명</th>\r\n");
      out.write("                                <th>구분</th>  \r\n");
      out.write("                                <th>가격</th>  \r\n");
      out.write("                                <th>재고</th>\r\n");
      out.write("                                <th>등록일</th>\r\n");
      out.write("                        </tr> \r\n");
      out.write("                    </thead>    \r\n");
      out.write("                    <tbody>      \r\n");
      out.write("                            <tr> \r\n");
      out.write("                                <td>1011</td>\r\n");
      out.write("                                <td>사과<br>500g</td>\r\n");
      out.write("                                <td>과일</td>\r\n");
      out.write("                                <td>4000원</td>\r\n");
      out.write("                                <td>100</td>\r\n");
      out.write("                                <td>2023-01-01</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr> \r\n");
      out.write("                                <td>1011</td>\r\n");
      out.write("                                <td>사과<br>500g</td>\r\n");
      out.write("                                <td>과일</td>\r\n");
      out.write("                                <td>4000원</td>\r\n");
      out.write("                                <td>100</td>\r\n");
      out.write("                                <td>2023-01-01</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr> \r\n");
      out.write("                                <td>1011</td>\r\n");
      out.write("                                <td>사과<br>500g</td>\r\n");
      out.write("                                <td>과일</td>\r\n");
      out.write("                                <td>4000원</td>\r\n");
      out.write("                                <td>100</td>\r\n");
      out.write("                                <td>2023-01-01</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>    \r\n");
      out.write("                    </table>\r\n");
      out.write("                 </article>\r\n");
      out.write("    \r\n");
      out.write("            <h4>주문현황</h4>\r\n");
      out.write("            <article class=\"h1\">\r\n");
      out.write("                <div class=\"plus\">+더보기</div>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr class=\"th\">\r\n");
      out.write("                            <th>주문번호</th>\r\n");
      out.write("                            <th>상품명</th>\r\n");
      out.write("                            <th>판매가격</th>\r\n");
      out.write("                            <th>수량</th>\r\n");
      out.write("                            <th>배송비</th>\r\n");
      out.write("                            <th>합계</th>\r\n");
      out.write("                            <th>주문자</th>\r\n");
      out.write("                            <th>주문일</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr class=\"td\">\r\n");
      out.write("                            <td>1011</td>\r\n");
      out.write("                            <td>사과 500g</td>\r\n");
      out.write("                            <td>4000원</td>\r\n");
      out.write("                            <td>2개</td>\r\n");
      out.write("                            <td>3000원</td>\r\n");
      out.write("                            <td>8000원</td>\r\n");
      out.write("                            <td>홍길동</td>\r\n");
      out.write("                            <td>2023-01-01</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"td\">\r\n");
      out.write("                            <td>1011</td>\r\n");
      out.write("                            <td>사과 500g</td>\r\n");
      out.write("                            <td>4000원</td>\r\n");
      out.write("                            <td>2개</td>\r\n");
      out.write("                            <td>3000원</td>\r\n");
      out.write("                            <td>8000원</td>\r\n");
      out.write("                            <td>홍길동</td>\r\n");
      out.write("                            <td>2023-01-01</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"td\">\r\n");
      out.write("                            <td>1011</td>\r\n");
      out.write("                            <td>사과 500g</td>\r\n");
      out.write("                            <td>4000원</td>\r\n");
      out.write("                            <td>2개</td>\r\n");
      out.write("                            <td>3000원</td>\r\n");
      out.write("                            <td>8000원</td>\r\n");
      out.write("                            <td>홍길동</td>\r\n");
      out.write("                            <td>2023-01-01</td> \r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </article>\r\n");
      out.write("    \r\n");
      out.write("            <h4>회원현황</h4>\r\n");
      out.write("            <article class=\"h1\">\r\n");
      out.write("                <div class=\"plus\">+더보기</div>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr class=\"th\">\r\n");
      out.write("                            <th>회원아이디</th>\r\n");
      out.write("                            <th>이름</th>\r\n");
      out.write("                            <th>닉네임</th>\r\n");
      out.write("                            <th>휴대폰</th>\r\n");
      out.write("                            <th>이메일</th>\r\n");
      out.write("                            <th>등급</th>\r\n");
      out.write("                            <th>회원가입일</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr class=\"td\">\r\n");
      out.write("                            <td>a101</td>\r\n");
      out.write("                            <td>김유신</td>\r\n");
      out.write("                            <td>유신<br>123</td>\r\n");
      out.write("                            <td>010-1234-1001</td>\r\n");
      out.write("                            <td>yusin123@naver.com</td>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td>2023-01-01</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"td\">\r\n");
      out.write("                            <td>a101</td>\r\n");
      out.write("                            <td>김유신</td>\r\n");
      out.write("                            <td>유신<br>123</td>\r\n");
      out.write("                            <td>010-1234-1001</td>\r\n");
      out.write("                            <td>yusin123@naver.com</td>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td>2023-01-01</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"td\">\r\n");
      out.write("                            <td>a101</td>\r\n");
      out.write("                            <td>김유신</td>\r\n");
      out.write("                            <td>유신<br>123</td>\r\n");
      out.write("                            <td>010-1234-1001</td>\r\n");
      out.write("                            <td>yusin123@naver.com</td>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td>2023-01-01</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </article>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <p class=copyright>\r\n");
      out.write("                Copyright(C)Farmstory All rights reserved.FARMSTORY ADMINISTRATOR Version 1.0.1\r\n");
      out.write("            </p>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
